---
- name: prueba bloques
  hosts: servera
  tasks:
    - name: instalar y configurar el plugin de yum versionlock
      block:
        - name: instalar paquete necesario para yum
          yum:
            name: yum-plugin-versionlock
            state: present

        - name: bloquear version de tzdata
          lineinfile:
            dest: /etc/yum/pluginconf.d/versionlock.list
            line: tzdata-2016j-1
            state: present
      when: ansible_distribution == "Red Hat"
      rescue:
        - name: revertir las acciones del bloque
          shell: /super/script/python.py
      always:
        - name: siempre reiniciar el servicio httpd
          service:
            name: httpd
            state: restarted
