---
- name: demonstrate the "in" keyword
  hosts: servera
  gather_facts: yes
  tasks:
    - name: install httpd using yum, where supported
      yum:
        name: httpd
        state: present
      when: >
         ( ansible_distribution == "RedHat" and
         ansible_distribution_version == "7.5" )
         or
         ( ansible_distribution == "Fedora" and
         ansible_distribution_version == "28" )
