---
- name: ejemplo stat
  hosts: servera
  tasks:
    - name: prueba stat
      stat:
        path: /tmp/miarchivo_que_no_existe
      register: stat_result

    #- name: fallar si el archivo no existe
    #  fail:
    #  when: not stat_result.stat.exists
    #
    - name: fallar si el archivo no existe
      assert:
        that:
        - stat_result.stat.exists
