---
- name: ejemplo files
  hosts: servera
  tasks:
    - name: crear archivo y configurar permisos
      file:
        path: /tmp/miarchivo
        owner: student
        group: student
        mode: 0640
        state: touch
        setype: samba_share_t

    - name: asegurar que el archivo /tmp/miarchivo siempre tenga el contexto de selinux samba_share_t
      sefcontext:
        target: /tmp/miarchivo
        setype: samba_share_t
        state: present
