---
- name: Prueba de Register con Loop
  hosts: servera
  gather_facts: no
  tasks:
    - name: Looping echo task
      shell: "echo This is my item: {{ item }}"
      loop:
        - one
        - two
      register: echo_results

    - name: Show echo_results variable
      debug:
        var: echo_results
